### ISSUE TITLE
Drop CUDA<11.8 builds?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/nvcc-feedstock#100]
Noticed that CI still builds 9.2, 10.0, 10.1, 10.2, 11.0, 11.1, all of which have already been dropped by conda-forge. Given the number of CI jobs, I'm wondering if this is still useful/necessary?

CC @conda-forge/nvcc

**Comment by h-vetinari** [comment]
I had placed this in the wrong repo (with the back and forth between the PRs... sorry), now fixed.

**Comment by jakirkham** [comment]
There are some legacy CUDA specific bits [in `conda-forge-ci-setup`]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/22b4448b3d9feda2f78f94149b68a015366c3a9e/recipe/install_cuda.bat#L15-L20 ) as well

Not to mention `cudatoolkit` has these too

Maybe having a meta-issue to cover all of these is good, which this can serve as that issue
