### ISSUE TITLE
CUDA 12.1 or 12.2 support

### ISSUE THREAD

**Issue by elgalu** [conda-forge/nvcc-feedstock#105]
Thanks for this feedstock! it would be great to have CUDA 12.1 or 12.2 support<3

**Comment by h-vetinari** [comment]
The CUDA infrastructure in conda-forge has changed substantially with 12.0 (see https://github.com/conda-forge/conda-forge.github.io/issues/1963). We have all 12.x versions, but not on this feedstock.
