### ISSUE TITLE
CMake has trouble verifying the CUDA compiler

### ISSUE THREAD

**Issue by carterbox** [conda-forge/nvcc-feedstock#29]
CMake will have trouble verifying that the CUDA compiler is functioning because it uses the location of the NVCC binary to find the other CUDA libraries and headers. Because NVCC is linked into the `CONDA_PREFIX`, CMake will search `CONDA_PREFIX/include` for the CUDA headers, not find them and then print an error message like (paraphrasing): `Could not find CUDA_INCLUDE_DIRS (found 10.1)`.

I believe linking the CUDA includes directory to `CONDA_PREFIX` solves the problem (Something like `ln -s ${CUDA_HOME}/include/* ${CONDA_PREFIX}/include/`).

If the `nvcc_linux-64` package exists to link the host NVCC installation to the Conda environment then it should also link the CUDA headers automatically?

**Comment by pearu** [comment]
What is the output of `echo $CXXFLAGS`?

**Comment by carterbox** [comment]
`-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/tomopy-1.7.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -I/usr/local/cuda/include`

**Comment by pearu** [comment]
Thanks. It is interesting that $CXXFLAGS contains unexpanded `$PREFIX`. Is this because the `cmake` is called from a `build.sh` script? If so, try adding
```
 -DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
```
to the `cmake` command line options line.

**Comment by carterbox** [comment]
Thanks for the suggestion. :smile: That works (probably in a more robust way than my solution), but like... what's the point of linking NVCC to the `CONDA_PREFIX` if I should tell CMake to look outside the `CONDA_PREFIX` for the CUDA headers and libraries? If this package just made sure that the desired `CUDA_HOME` was at the front of the `PATH` or linked all of the things, then I wouldn't have to do anything. :man_shrugging:

**Comment by jakirkham** [comment]
Took a brief look at TomoPy and admittedly don't know much about what is going on there, but think it may be using legacy CMake CUDA support, which may be part of the problem here. So have raised issue ( https://github.com/tomopy/tomopy/issues/451 ). Again don't know much about TomoPy. So may be missing things.

**Comment by jakirkham** [comment]
Is this still an issue?

cc @kkraus14 @robertmaynard (for vis)

**Comment by robertmaynard** [comment]
This should be fixed in CMake 3.20 as it now asks `nvcc` where to find the headers, instead of computing it based on the location of `nvcc`.

**Comment by carterbox** [comment]
I haven't has an issues since I added  `-DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME` to my build, but also I just tested a build without setting `-DCUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME` and it works.

Not sure about CMake 3.20 because it isn't yet available on conda-forge.

**Comment by jakirkham** [comment]
> Not sure about CMake 3.20 because it isn't yet available on conda-forge.

Please see PR ( https://github.com/conda-forge/cmake-feedstock/pull/137 )

**Comment by jakirkham** [comment]
Also thanks for the update. Glad to hear things are working better 😄
