### ISSUE TITLE
Windows strategy

### ISSUE THREAD

**Issue by scopatz** [conda-forge/nvcc-feedstock#48]
HI @conda-forge/nvcc & @jaimergp, 

I wanted to start a discussion about how to move forward with this on Windows.  Do we have have a sense of how to enable nvcc on Windows in general? Is NVCC able to compile against previous versions of the ABI?  We now have the ability to `choco install cuda` relatively easily, but [only version 11.0+ seems to actually work](https://github.com/conda-forge/cudatoolkit-feedstock/pull/13#issuecomment-716755959).

**Comment by isuruf** [comment]
>  Is NVCC able to compile against previous versions of the ABI? 

Nope

https://github.com/microsoft/vcpkg/blob/8054263f15c8400d6df5fff55fae97394e187368/scripts/azure-pipelines/windows/provision-image.txt seems to install cuda 10.1 on azure. PRs are welcome to `conda-forge-ci-setup` to install cuda if `cuda_compiler_version` is in `CONFIG`

**Comment by jaimergp** [comment]
According to the comments in https://chocolatey.org/packages/cuda, old versions are being removed after a while, so I don't know if that's a good idea.

What we did in `omnia` involved getting the installers from Nvidia directly. [See here](https://github.com/omnia-md/conda-dev-recipes/blob/master/.azure-pipelines/azure-pipelines-windows.yml#L25-L146).

**Comment by scopatz** [comment]
@isuruf - why do you think this needs to be done as part of `conda-forge-ci-setup`? Couldn't this be a step that is added as part of conda-smithy?

**Comment by scopatz** [comment]
Pinging this again

**Comment by jaimergp** [comment]
I think this can be closed after #49

**Comment by kkraus14** [comment]
Closed by #49
