### ISSUE TITLE
[Windows] CUDA_HOME cannot be found under some circumstances

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/nvcc-feedstock#53]
Just making a note to self here.

Getting CUDA to work on Windows involves:

a) `conda-forge-ci-setup` installing the CUDA+drivers package from Nvidia. This also exports `CUDA_HOME` & `CUDA_PATH`, and adds `CUDA_HOME\bin` to `PATH` using [Azure echo magic](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/install_cuda.bat#L122-L125).
b) This `nvcc` wrapper finds `CUDA_HOME` and and exposes it to `conda-build` through the activation scripts. If for some reason this is not defined, it still tries to find `nvcc.exe` on `PATH` and work from that.

* On feedstocks like OpenMM this works as expected. Step [(a)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245139&view=logs&j=578ef24e-67b2-50f2-cae0-20f301d66dba&t=a5a45eab-9113-5a3c-ed3e-221d61d024e9&l=44) and [(b)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245139&view=logs&j=578ef24e-67b2-50f2-cae0-20f301d66dba&t=def23df8-6bfb-5cc7-ad94-bd29cc3cc88c&l=325). 
* However, this is not the case in [Prismatic](https://github.com/conda-forge/prismatic_split-feedstock/pull/17). [Step (a)](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245371&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=ac199efb-6791-5d5e-770f-2831854227bc&l=89) works ok, but [(b) does not](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=245371&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0bf03e01-0bec-5b85-5316-b1633322e895&l=273). CUDA_HOME never reached this part.

One difference is that OpenMM is a classic recipe with a single output, and Prismatic uses multiple outputs. Could this explain the different behavior? I am not sure why, so I am leaving this here to investigate later.

**Comment by isuruf** [comment]
Not sure the reason, but use https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/master/recipe/run_conda_forge_build_setup_win.bat#L72

**Comment by jaimergp** [comment]
Thanks! Adding those changes to https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/131

**Comment by h-vetinari** [comment]
Having the same problem in https://github.com/conda-forge/faiss-split-feedstock/pull/19, sample [CI run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=250255&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=212).

@jaimergp mentioned in that PR that it's probably due to being a multi-output recipe...

**Comment by jaimergp** [comment]
While the root problem has not been fixed (the env vars set by `conda-forge-ci-setup` should be there!), `nvcc` now has a workaround to look in the default installation locations (which CMake uses too, but for some reason it does not work), implemented by #52.

**Comment by jakirkham** [comment]
Thanks Jaime! 😄
