### ISSUE TITLE
Build CUDA 11.x for ppc64le?

### ISSUE THREAD

**Issue by leofang** [conda-forge/nvcc-feedstock#73]
Currently we only build CUDA 10.2 on ppc64le:
https://github.com/conda-forge/nvcc-feedstock/blob/408c93112830bfbd8707ea5bc8a4be7cb6b94462/recipe/meta.yaml#L20
It looks like we have everything ready for removing this restriction?

**Comment by jakirkham** [comment]
cc @jaimergp (as I think you know more where things stand here)

**Comment by leofang** [comment]
My understanding based on https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cuda#adding-support-for-a-new-cuda-version is we need the following works for supporting a new CUDA version on Linux:
- docker image (done)
- cudatoolkit (done)
- nvcc (this issue)

and then we fire up the migrator, so @jaimergp this should be the last blocker?

**Comment by jaimergp** [comment]
Yes, I recall the only restriction was that we didn't have the Docker images back then.

**Comment by jakirkham** [comment]
Though it is worth noting, we have had some issues building Docker images for `ppc64le` recently ( https://github.com/conda-forge/docker-images/issues/190 )

**Comment by jakirkham** [comment]
Looks like that issue has cleared up. New images should now be available.
