### ISSUE TITLE
How to use this metapackage in recipes

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/nvcc-feedstock#8]
Hi!

I want to use the (now published) metapackage in https://github.com/conda-forge/staged-recipes/pull/9102, but I don't see it in the `conda-forge` channel. It does appear in `nvidia` though.

Also, do I need to modify any of the supporting infrastructure (YAML/sh files outside the recipes directory, mainly)?

Thanks!

**Comment by jakirkham** [comment]
It is published in `conda-forge`. However as it is a compiler package, it is named `nvcc_{ platform }-{ arch }`. So it is `nvcc_linux-64`.

Independently it appears the package name wasn't showing up correctly. So have requested ( https://github.com/conda-forge/nvcc-feedstock/issues/9 ) a re-render PR ( https://github.com/conda-forge/nvcc-feedstock/pull/10 ), which corrects the package name in the README.

PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/14 ) should provide some good guidance. The important things are adding a `conda_build_config.yaml` to the recipe with the necessary GPU bits. Ultimately we'd like to upstream this so it doesn't need to live in the feedstock. Also you need to depend on the CUDA compiler in your `build` requirements.

**Comment by jakirkham** [comment]
If you have any other questions, please let us know. 🙂

**Comment by jakirkham** [comment]
FYI the `conda_build_config.yaml` GPU bits referred to earlier are no longer needed as these have been upstreamed into conda-forge-pinning. ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/285 )

As a result, a recipe only needs to add `{{ compiler("cuda") }}` to `requirements/build` and then decide whether to [support a CPU-only build]( https://github.com/conda-forge/ucx-split-feedstock/blob/0e3d580f5707c9a13d1dc459ddaeb49183c322a3/recipe/meta.yaml#L49 ) or [not]( https://github.com/conda-forge/openmm-feedstock/blob/7ca118a1ef45102c3cbf9d420e3a2d0c19bde503/recipe/meta.yaml#L15 ). If this is added to an existing feedstock, re-rendering will be required after listing the compiler.

**Comment by isuruf** [comment]
> If this is added to an existing feedstock, re-rendering will be required after listing the compiler.

You still can't use this in staged-recipes. So only existing feedstocks work.

**Comment by jakirkham** [comment]
That's correct. Tracking staged-recipes work in issue ( https://github.com/conda-forge/staged-recipes/issues/9773 ).

**Comment by jakirkham** [comment]
Though it's worth noting that staged-recipes will produce a working feedstock after conversion (despite being unable to performing the testing their currently).
