### ISSUE TITLE
conda-forge/nvcc vs nvidia/cuda-nvcc

### ISSUE THREAD

**Issue by ngam** [conda-forge/nvcc-feedstock#93]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Is it possible to include the content of nvidia/cuda-nvcc here?

https://anaconda.org/nvidia/cuda-nvcc

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by kkraus14** [comment]
No it is not until NVIDIA either changes their EULA or grants conda-forge explicit permission to redistribute `nvcc`.
